---
- name: Install nginx
  apt:
    update_cache: yes
    name: nginx
    state: present

- name: Create domain directory
  file:
    path: "/var/www/{{ domain }}"
    state: directory

- name: Create index.php file
  copy:
    dest: /var/www/{{ domain }}/phpinfo.php
    content: |
      <?php phpinfo(); ?>
   
- name: Generate SSL certificate
  shell: |
    openssl req \
    -x509 \
    -newkey rsa:2048 \
    -nodes \
    -days 365 \
    -keyout /etc/ssl/private/{{ domain }}-selfsigned.key \
    -out /etc/ssl/certs/{{ domain }}-selfsigned.crt \
    -subj "/C=/ST=/L=/O=/CN={{ domain }}"

    openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

  when: generate_ssl_certs is true 
  run_once: true

- name: Generate nginx config
  template:
    src: nginx_config_template.j2
    dest: "/etc/nginx/sites-available/{{ domain }}.conf"

- name: Enable nginx site
  file:
    src: "/etc/nginx/sites-available/{{ domain }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ domain }}.conf"
    state: link
    
- name: Restart nginx
  service:
    name: nginx
    state: restarted
